name: 'Bundlesize'
description: 'Get info about bundle size changes'
inputs:
  github_token:
    required: true
    description: The token provided by GitHub Actions via secrets.GITHUB_TOKEN
runs:
  using: 'node12'
  main: 'dist/index.js'
